### PR TITLE
Restore Emitter callbacks for success and failure (close #339)

### LINKED ISSUE #339: Restore Emitter callbacks for success and failure
Older versions of the Java tracker had `RequestCallback`. Users could provide methods to call when events were successfully sent, or failed to send, via the `RequestCallback` interface. The `onFailure()` method could be given a list of `Event` objects, allowing the user to retrack them as if they were brand new. This was the only way to retry the requests.

Since v0.12.0, the Java tracker automatically retries events indefinitely. As part of the restructuring, `RequestCallback` was removed.

Callbacks can still be useful, however, so let's reinstate with a better implementation.

### PR DESCRIPTION
**Pull request by mscwilson**
For issue #339.

Allows users to provide callbacks to `BatchEmitter`. The success callback will be called after a request is successfully sent. The failure callback will be called after a request gets a response code other than 2xx, or if the emitter's storage is full.

A new EmitterCallback interface is provided for the callbacks, along with a new enum, FailureType, for the failure callback. The three possible failures are: `CONNECTION_FAILURE` (exceptions during event sending); `REJECTED_BY_COLLECTOR` (non-2xx HTML request codes); or `TRACKER_STORAGE_FULL`.

Events are added to the storage in two places, therefore the `TRACKER_STORAGE_FULL` can occur in two places. The standard occasion is when new events are added to the `BatchEmitter` by the `Tracker` object. However, if events fail to send and should be retried, they are added back into the storage queue inside the `InMemoryEventStore`. If the queue is full, newer events are removed and deleted to make space for the returning older events.

This means that the EmitterCallback should be shared across `BatchEmitter` and `InMemoryEventStore`. I added a Builder to `InMemoryEventStore` to avoid having a confusing collection of constructors.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitter.java [hunk 1]
```diff
@@ -379,6 +410,7 @@ private Runnable getPostRequestRunnable(int numberOfEvents) {
                 LOGGER.error("BatchEmitter event sending error: {}", e.getMessage());
                 if (batchedEvents != null) {
                     eventStore.cleanupAfterSendingAttempt(true, batchedEvents.getBatchId());
+                    callback.onFailure(FailureType.CONNECTION_FAILURE, true, new ArrayList<>(batchedEvents.getPayloads()));
```
Comment (matus-tomlein) [inline src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitter.java:413]: I think the connection failure error is represented as the -1 status code returned from the HTTP client, see the [OkHttpClientAdapter implementation](https://github.com/snowplow/snowplow-java-tracker/blob/issue/339-callbacks/src/main/java/com/snowplowanalytics/snowplow/tracker/http/OkHttpClientAdapter.java#L122). Perhaps we should check for that case among the if cases above?

I'm not actually sure what Exception is caught in this catch clause – I tried to remove it and nothing complained, all tests passed. Do you have any idea what is it for? If we could make the failure type more specific to the problem, that would be great.

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitter.java [hunk 2]
```diff
@@ -276,6 +302,7 @@ public boolean add(final TrackerPayload payload) {
         
         if (!result) {
             LOGGER.error("Unable to add payload to emitter, emitter buffer is full");
+            callback.onFailure(FailureType.TRACKER_STORAGE_FULL, false, Collections.singletonList(payload));
```
Comment (matus-tomlein) [inline src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitter.java:305]: This may be just my personal preference, but I find it a bit confusing that we call the callback for the `TRACKER_STORAGE_FULL` failure type in two different classes (BatchEmitter and InMemoryStorage). I think it'd be better to define who is responsible for handling the failure type and handle all its instances in that class. If we can't handle all callbacks in the Emitter (which I think would be clearer than delegating the responsibility to other places), could we handle all `TRACKER_STORAGE_FULL` errors in the InMemoryStorage?

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/FailureType.java [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+ * software distributed under the Apache License Version 2.0 is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the Apache License Version 2.0 for the specific language governing permissions and limitations there under.
+ */
+package com.snowplowanalytics.snowplow.tracker.emitter;
+
+/**
+ * The supported failure options for EmitterCallback.
+ */
+public enum FailureType {
```
Comment (matus-tomlein) [inline src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/FailureType.java:18]: Could we also comment and explain when the individual options in the enum occur for the users?

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/InMemoryEventStore.java [hunk 4]
```diff
@@ -113,7 +143,8 @@ public void cleanupAfterSendingAttempt(boolean needRetry, long batchId) {
                 boolean result = eventBuffer.offerFirst(payloadToReinsert);
                 if (!result) {
                     LOGGER.error("Event buffer is full. Dropping newer payload to reinsert older payload");
-                    eventBuffer.removeLast();
+                    TrackerPayload removedPayload =  eventBuffer.removeLast();
+                    callback.onFailure(FailureType.TRACKER_STORAGE_FULL, false, Collections.singletonList(removedPayload));
```
Comment (matus-tomlein) [inline src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/InMemoryEventStore.java:147]: I commented about this above, but the more I think about it, the more it doesn't feel right for the InMemoryStorage to be given the responsibility for calling the EmitterCallback – I think the Emitter should fire the EmitterCallback for all the handled cases. If we distribute the calls in different places, it becomes more difficult to reason about when and how many times it is called. Also the storage layer can be replaced by users and the EventStore API does not provide them with the callback object in case they use a custom storage, so the storage full error won't be called in that case.

I think it would be better if the EventStore interface explicitly captured cases when the error occurs. Perhaps this function could return a list of payloads that could not be saved to the storage? Or we could make a dedicated callback for this specific error (not the EmitterCallback) and pass it as argument to the functions where it can occur (the Emitter would then listen to the callback and forward the errors to the EmitterCallback)?

Btw, it's awesome that you also capture this storage error in the EmitterCallback!

File: src/test/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitterTest.java [hunk 5]
```diff
@@ -355,6 +355,145 @@ public void noRetryAfterDenylistResponseCode() throws InterruptedException {
...
+        class TestCallback implements EmitterCallback {
+            List<TrackerPayload> payloads;
+
+            @Override
+            public void onSuccess(List<TrackerPayload> payloads) {
+                this.payloads = payloads;
+            }
+
+            @Override
+            public void onFailure(FailureType failureType, boolean willRetry, List<TrackerPayload> payloads) {
```
Comment (matus-tomlein) [inline src/test/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitterTest.java:369]: Perhaps we should throw an error in this case? Similar in the tests below for the cases that are not expected.

**Review by matus-tomlein — COMMENTED** [review]
Looks great! I just had a few comments, let me know if that makes sense.

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitter.java (hunk 1 above)
Comment (mscwilson) [reply src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitter.java:413]: Most likely InterruptedException? I couldn't work out how to test it

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitter.java (hunk 2 above)
Comment (mscwilson) [reply src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitter.java:305]: Nice idea!

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/InMemoryEventStore.java (hunk 4 above)
Comment (mscwilson) [reply src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/InMemoryEventStore.java:147]: The code would definitely be neater if only the Emitter has the EmitterCallback. I'll think about this callback idea

File: src/test/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitterTest.java (hunk 5 above)
Comment (mscwilson) [reply src/test/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitterTest.java:369]: What would the error do?

Comment (matus-tomlein) [reply src/test/java/com/snowplowanalytics/snowplow/tracker/emitter/BatchEmitterTest.java:369]: I just wanted it to fail the test in case the wrong callback is called – to be sure that only the `onSuccess` callback is called and not the `onFailure` (or vice versa in other test cases). Otherwise you could have an implementation that calls both callbacks and passes the tests. (btw, forgot to say but this is really is just a nitpick)

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/InMemoryEventStore.java [hunk 6]
```diff
@@ -99,11 +98,13 @@ public BatchPayload getEventsBatch(int numberToGet) {
      *
      * @param needRetry if true, move events back to the buffer instead of deleting
      * @param batchId the ID of the batch of events
+     * @return newer TrackerPayloads deleted from the queue to make space for older payloads
```
Comment (matus-tomlein) [inline src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/InMemoryEventStore.java:101]: Btw, just realizing now that I am a bit confused by this behaviour – Why would we remove newer events to make space for older events that failed to be sent to the collector? I would expect that the older events are dropped first and newer kept. No need to change this here, I just found it a bit weird.

**Review by matus-tomlein — APPROVED** [review]
LGTM! 👍 

The changes in the EventStore interface are breaking changes so please remember to mention that in the upgrading guide.

File: src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/InMemoryEventStore.java (hunk 6 above)
Comment (mscwilson) [reply src/main/java/com/snowplowanalytics/snowplow/tracker/emitter/InMemoryEventStore.java:101]: When the storage is full and new events arrive, they're dropped in favour of keeping the old ones that are already buffered. This is for consistency with that.
Why we chose to do that, I'm not sure. IIRC all the trackers have this behaviour.
